---
- name: "Play [Libvirt]: Apply workstation Bastion Vault host prerequisites"
  hosts: workstation
  become: true
  gather_facts: true
  vars_files:
    - ../../workstation-topology.yaml
  roles:
    - workstation_libvirt
